export interface LoveReason {
  id: number;
  text: string;
}

export const LOVE_REASONS: LoveReason[] = [
  { id: 1, text: "Your smile can brighten even my darkest day." },
  { id: 2, text: "Your adorable puppy eyes melt my heart every single time." },
  { id: 3, text: "Watching you dominate in Rocket League makes me smile." },
  { id: 4, text: "Your rings (ifykyk ❤️) will always have a special place in my heart." },
  { id: 5, text: "You’re the only person who knows exactly how to manao me." },
  { id: 6, text: "Your dressing sense is effortlessly beautiful." },
  { id: 7, text: "I could listen to you sing forever." },
  { id: 8, text: "Watching you dance makes me fall for you all over again." },
  { id: 9, text: "Your emotional maturity inspires me every day." },
  { id: 10, text: "The effort you put into our relationship never goes unnoticed." },
  { id: 11, text: "Even during exams, you travel back and forth just to see me, and I’ll never stop appreciating that." },
  { id: 12, text: "Your laugh is my favorite sound." },
  { id: 13, text: "You make every ordinary day feel special." },
  { id: 14, text: "You make me want to become a better person." },
  { id: 15, text: "You make me feel safe, loved, and understood." },
  { id: 16, text: "You always support my dreams." },
  { id: 17, text: "You somehow know what I’m thinking before I say it." },
  { id: 18, text: "Every hug from you feels like home." },
  { id: 19, text: "Every call with you instantly makes my day better." },
  { id: 20, text: "You choose us, every single day." },
  { id: 21, text: "Because your “good morning” texts somehow make every morning better." },
  { id: 22, text: "Because your “good night” wishes always make me sleep with a smile." },
  { id: 23, text: "Because you somehow know when something is bothering me, even when I say “I’m fine.”" },
  { id: 24, text: "Because every hug from you feels like home." },
  { id: 25, text: "Because your excitement is contagious." },
  { id: 26, text: "Because you never stop trying for us." },
  { id: 27, text: "Because you make distance feel a little less painful." },
  { id: 28, text: "Because you’re the first person I want to tell whenever something good happens." },
  { id: 29, text: "Because you’re also the first person I want when life gets difficult." },
  { id: 30, text: "Because every call with you somehow ends too quickly." },
  { id: 31, text: "Because you laugh at my stupid jokes… even the bad ones." },
  { id: 32, text: "Because you’ve seen my flaws and still choose me." },
  { id: 33, text: "Because you make me feel like I’m enough." },
  { id: 34, text: "Because your little expressions are cuter than you realize." },
  { id: 35, text: "Because I never get tired of hearing your voice." },
  { id: 36, text: "Because every memory with you becomes one of my favorites." },
  { id: 37, text: "Because you’re genuinely kind to people." },
  { id: 38, text: "Because you’re stronger than you give yourself credit for." },
  { id: 39, text: "Because you always find a way to make me smile." },
  { id: 40, text: "Because your happiness automatically becomes my happiness." },
  { id: 41, text: "Because your sleepy voice is one of the cutest things ever." },
  { id: 42, text: "Because you always try to understand me before judging me." },
  { id: 43, text: "Because before we ever spoke, I told our mutual friend, “Maybe in some alternate universe she’ll talk to me.” I never imagined this universe would let me call you mine. And somehow, it’s only fitting that this is Reason #43 because every step of our story has quietly been saying 143 all along. 💕" },
  { id: 44, text: "Because you support my dreams without making me feel silly." },
  { id: 45, text: "Because you remember tiny little details about me." },
  { id: 46, text: "Because you’re beautiful without even trying." },
  { id: 47, text: "Because every picture of you somehow becomes my favorite." },
  { id: 48, text: "Because your little jealous moments are secretly adorable." },
  { id: 49, text: "Because you’re patient with me, even when I make things difficult." },
  { id: 50, text: "Because you’ve taught me what real effort looks like." },
  { id: 51, text: "Because you make ordinary moments unforgettable." },
  { id: 52, text: "Because you’re my comfort person." },
  { id: 53, text: "Because you make me laugh when I least expect it." },
  { id: 54, text: "Because talking to you never feels like a chore." },
  { id: 55, text: "Because every date with you feels exciting, no matter how simple." },
  { id: 56, text: "Because your smile deserves to be protected forever." },
  { id: 57, text: "Because you somehow make every outfit look amazing." },
  { id: 58, text: "Because you never stop caring." },
  { id: 59, text: "Because you’ve become my favorite habit." },
  { id: 60, text: "Because life feels more colorful with you in it." },
  { id: 61, text: "Because you’re my peace after a chaotic day." },
  { id: 62, text: "Because I can be my weird self around you." },
  { id: 63, text: "Because you never make me feel alone." },
  { id: 64, text: "Because I trust you with my heart." },
  { id: 65, text: "Because you’ve made these 100 days the happiest chapter of my life." },
  { id: 66, text: "Because you make me want to become a better man." },
  { id: 67, text: "Because you’re incredibly thoughtful." },
  { id: 68, text: "Because every little thing reminds me of you." },
  { id: 69, text: "Because I still smile when your name pops up on my phone." },
  { id: 70, text: "Because your hugs fix things words can’t." },
  { id: 71, text: "Because every goodbye only makes me more excited for the next hello." },
  { id: 72, text: "Because you’re worth every kilometer, every train, every wait, and every second." },
  { id: 73, text: "Because you always make time for us." },
  { id: 74, text: "Because you understand that love is shown through actions." },
  { id: 75, text: "Because your heart is as beautiful as your face." },
  { id: 76, text: "Because you’ve become my favorite notification." },
  { id: 77, text: "Because I never get bored of you." },
  { id: 78, text: "Because every festival feels more special with you." },
  { id: 79, text: "Because every celebration is better when you’re part of it." },
  { id: 80, text: "Because you always make me feel important." },
  { id: 81, text: "Because you forgive me when I genuinely try to improve." },
  { id: 82, text: "Because your love makes me feel lucky every single day." },
  { id: 83, text: "Because you inspire me to dream bigger." },
  { id: 84, text: "Because you’re my safe place." },
  { id: 85, text: "Because even silence with you feels comfortable." },
  { id: 86, text: "Because you’re my favorite adventure." },
  { id: 87, text: "Because you make love feel effortless." },
  { id: 88, text: "Because you’re the person I thank God for." },
  { id: 89, text: "Because every little achievement feels better when I can share it with you." },
  { id: 90, text: "Because you’ve given me countless reasons to smile in just 100 days." },
  { id: 91, text: "Because you’re my favorite “what if” that became reality." },
  { id: 92, text: "Because every day with you teaches me something new about love." },
  { id: 93, text: "Because you’re beautiful inside and out." },
  { id: 94, text: "Because you always make me feel heard." },
  { id: 95, text: "Because no matter what happens, I always want to come back to you." },
  { id: 96, text: "Because loving you is the easiest thing I’ve ever done." },
  { id: 97, text: "Because even after 100 days, I still get butterflies because of you." },
  { id: 98, text: "Because every future I imagine has you standing beside me." },
  { id: 99, text: "Because every single day, you give me another reason to love you even more than yesterday." },
  // Reason #100
  {
    id: 100,
    text: `I promised you 100 reasons… but the truth is, I’d never be able to stop at 100. Every single day you give me a brand new reason to fall in love with you all over again.

Happy 100 Days, WIFEYYY.

Thank you for choosing me, loving me, forgiving me, supporting me, and growing with me.

Here’s to hundreds, thousands, and forever more.

I love you endlessly. ❤️`
  }
];
